# Generated by Django 2.2.24 on 2021-10-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.App', verbose_name='App')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan', verbose_name='Plan')),
            ],
            options={
                'unique_together': {('app', 'plan')},
            },
        ),
    ]
