# Generated by Django 2.2.24 on 2021-10-27 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20211027_0125'),
        ('plans', '0001_initial'),
        ('subscriptions', '0002_auto_20211027_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App', verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan', verbose_name='Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('app', 'plan')},
        ),
    ]
